-- MySQL Script generated by MySQL Workbench
-- dom 30 sep 2018 19:36:30 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema recipes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `recipes` ;

-- -----------------------------------------------------
-- Schema recipes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `recipes` DEFAULT CHARACTER SET utf8 ;
USE `recipes` ;

-- -----------------------------------------------------
-- Table `recipes`.`recipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recipes`.`recipe` ;

CREATE TABLE IF NOT EXISTS `recipes`.`recipe` (
  `idrecipe` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `description` MEDIUMTEXT NULL,
  PRIMARY KEY (`idrecipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recipes`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recipes`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `recipes`.`ingredients` (
  `idingredients` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(500) NULL,
  `recipe_idrecipe` INT NOT NULL,
  PRIMARY KEY (`idingredients`),
  INDEX `fk_ingredients_recipe_idx` (`recipe_idrecipe` ASC),
  CONSTRAINT `fk_ingredients_recipe`
    FOREIGN KEY (`recipe_idrecipe`)
    REFERENCES `recipes`.`recipe` (`idrecipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
